CREATE DATABASE PASSWORDMANAGER;
USE PASSWORDMANAGER;
DROP TABLE CARD;
CREATE TABLE CARD
( ID VARCHAR(50),BANK_NAME VARCHAR(25),CARD_TYPE VARCHAR(20),MPIN INT,PIN INT);
select * from card;
alter table card add primary key(ID);
